### ISSUE TITLE
Looks very promising

### ISSUE THREAD

**Issue by berrg** [dfee/rbx#26]
Looks great, but could you make a more advance typescript example. E.g. a page with navigation bar and navigation?

**Comment by dfee** [comment]
So the biggest problem – for what I think you're getting at – is that the examples are written in JS, whereas the package is advertised as being written in TS.

If this is your gripe – I get it. I don't know if if's possible to write TS in `mdx` files. Also, I wonder if that'd potentially turn off usage for non-TS users (who can still use this package!).

I would point you to the `examples/` dir that has two typescript examples in it. If you think a more robust demo is needed, I might be able to hack one together, but of course the extra work on maintenance for all these extra packages really adds up!

Thoughts?
