### ISSUE TITLE
Examples don't provide the import

### ISSUE THREAD

**Issue by pedromagalhaes** [dfee/rbx#32]
Hi all,

I've been using this framework and so far so good, but it gets time consuming to figure out what are the imports necessary for each component, element, etc. I think this is a bit frustration for new comers to the framework. The documentation in Rbx website doesnt seem to provide the Imports in the examples. Is there any reason for this?

Thanks, Pedro

**Comment by dfee** [comment]
Hey Pedro –

All "root" components can be imported directly from `rbx`, that is:
`import { Button, Column, Dropdown } from 'rbx';`

Some components also act as a container for other components, and make those other components available as properties. I.e. `Button.Group`, `Column.Group`, `Dropdown.Menu`, etc.

If you look at the API section on any page, you'll see the component's name indicates its usage. On the [`Dropdown` docs for example](https://dfee.github.io/rbx/components/dropdown), you'll see API declarations for:
* `Dropdown` (import directly from 'rbx')
* `Dropdown.Content` (available on the `Dropdown` component you've imported from 'rbx')
* etc.

**Comment by pedromagalhaes** [comment]
Ok thanks for the quick reply.
