### ISSUE TITLE
Change order of className?

### ISSUE THREAD

**Issue by eirikhm** [dfee/rbx#43]
Hi!

We are evaluating rbx for a new project, but are experiencing some problems when using the `as` prop.

Let's say we have some columns, and we'd like to align content to the bottom for one of them:
```jsx
 <Column.Group>
  <Column size={"half"} as={VerticalAlignedColumn}>
    Vertical content
  </Column>
  <Column size={"half"}>
    Normal content
  </Column>
</Column.Group>
```

In this scenario `VerticalAlignedColumn` is a styled component which sets the following:

```css
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
```

This does not work at the moment due to the order passed to `className` inside `Column`:

```jsx 
<Generic className={classNames("column", ...rest
```

Would it be possible to change the order so that className from components supplied by `as` would get precedence?

This is also relevant when specifying `className` directly on `Column` etc

**Comment by dfee** [comment]
I'm not sure I understand what you're getting at. Here is a quick demo I put together, but couldn't reproduce your issue: https://codesandbox.io/s/zwr4l3jo3m

**Comment by eirikhm** [comment]
Thanks for taking the time to investigate. I was mistaken. The core of the problem is https://stackoverflow.com/a/29695391/891691

Solved by running `import "rbx/index.css";` early as possible.
