### ISSUE TITLE
Next.js 8 - Attempted import error: 'Navbar' is not exported from 'rbx'.

### ISSUE THREAD

**Issue by pedromagalhaes** [dfee/rbx#46]
Hi, I was using many RBX UI comonents in a CMS, with Next.js 7
After upgrading to Next.js to version 8, all the components from RBX are giving error. 

`./components/Header.js
Attempted import error: 'Navbar' is not exported from 'rbx'.`

This is my import in the page:
`import { Navbar } from 'rbx'`

Do you have any solution for this, or a fix for it in a next release?

Thank you

**Comment by pedromagalhaes** [comment]
In order to solve this issue with Next.js 8 upgrade, we now have to import the rbx components in a different way, i.e. `import { Navbar } from 'rbx/components'`

**Comment by dfee** [comment]
As you can see from my most recent merge into the master branch, I added a `with-nextjs` example: https://github.com/dfee/rbx/tree/master/examples/with-nextjs

I couldn't reproduce your issue, however. It seems that importing directly from `rbx` works fine. Have you tried deleting node_modules and reinstalling? Maybe this is one of those issues?

**Comment by pedromagalhaes** [comment]
Hi dfee, thanks a lot for answering quickly. 

I cannot say the project in the examples folder works, because I have several issues when I try to start it with the dist relative folder generated from the root project. 

In this example project there are some assumptions that we have the "make" npm installed, and the .dist folder is already generated in a relative path to the root folder. 

However, even after I install "make" globally I get the following error in the "make build" script from the root project (i.e. /rbx/package.json) 

`$ yarn build
yarn run v1.13.0
$ make build
(node:13428) UnhandledPromiseRejectionWarning: undefined
(node:13428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a pro
mise which was not handled with .catch(). (rejection id: 1)
(node:13428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-
zero exit code.
make × ERR  not found: make-build
`

I would like to give it a try to all the examples, specially the "with-nextjs"

Let me know if Im missing some installing or script to workaround the issue above. 

Thank you

**Comment by dfee** [comment]
Are you using Windows? I know nothing about the [npm make](https://www.npmjs.com/package/make) and am using the [GNU make](https://www.gnu.org/software/make/) which ships with MacOS and Linux.

Can you confirm what `make` you're using?

**Comment by pedromagalhaes** [comment]
Hi yes im using windows. I will double check this configuration again. Its not an issue anymore. Thank you
