### ISSUE TITLE
Gatsby build error: window is not defined

### ISSUE THREAD

**Issue by benweier** [dfee/rbx#5]
I'm receiving an error when attempting to build a GatsbyJS site using rbx.

```
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://gatsby.app/debug-html

> 1 | export const canUseDOM = () => !(window === undefined ||
    |        ^
  2 |     window.document === undefined ||
  3 |     window.document.createElement === undefined);
  4 | export const combineRefs = (...refs) => {


  WebpackError: ReferenceError: window is not defined

  - utils.js:1 canUseDOM
    [lib]/[rbx]/utils.js:1:8

  - navbar-container.js:53 NavbarContainer.manageHtmlAttributes
    [lib]/[rbx]/components/navbar/navbar-container.js:53:22

  - navbar-container.js:25 NavbarContainer.render
    [lib]/[rbx]/components/navbar/navbar-container.js:25:1
```

The error message indicates that [canUseDOM](https://github.com/dfee/rbx/blob/4257cb815065061e9f6441bbd8c81dea74e3081f/src/utils.ts#L8) is the culprit from the `navbar-container.js` file but I imagine `modal-container.js` would produce the same result.

Because Gatsby builds in a node environment, `window` is never declared. I was able to resolve this by modifying `node_modules/rbx/utils.js` to be safer with

```
-export const canUseDOM = () => !(window === undefined ||
+export const canUseDOM = () => !(typeof window === 'undefined' ||
```

I intended to make a pull request with this change but it's now producing a linting error

```
Avoid typeof x === 'undefined' comparisons. Prefer x == undefined or x === undefined: typeof window === 'undefined'
```

**Comment by dfee** [comment]
Thanks to @jasonblalock's help, this is now resolved in `v2.0.2` which is published on npm.
