### ISSUE TITLE
Function components cannot be given refs

### ISSUE THREAD

**Issue by michaelhly** [dfee/rbx#52]
Hello, I am trying to render a Navbar Item as a NavLink component from react-router-dom (i.e. ` <Navbar.Item as={NavLink}> ... </Navbar.Item>`).  

I am using React Hooks so my entire Navbar component is a functional component. I'm not sure if this is a problem on my end or a problem with Navbar.Item.Container or Generic.

Here is the warning I am getting:
![Screen Shot 2019-04-03 at 2 29 47 PM](https://user-images.githubusercontent.com/24895862/55508321-469a4100-561f-11e9-91de-232821bf6aa5.png)

This warning does not come up when using `NavLink` by itself.

**Comment by dfee** [comment]
Can you share some additional code, or perhaps make a codesandbox example?

**Comment by michaelhly** [comment]
Hi! Here is a CodeSandBox example https://codesandbox.io/s/3xp0q12kz6.

**Comment by ReeganExE** [comment]
Any update? I have the same issue.

```jsx
import React from 'react'
import { Navbar } from 'rbx'
import { NavLink } from 'react-router-dom'

export default () => (
  <Navbar color="light" fixed="top">
    <Navbar.Brand>
      <Navbar.Item href="/">
        <img src="test.img" width="32" height="32" />
      </Navbar.Item>
      <Navbar.Burger />
    </Navbar.Brand>
    <Navbar.Menu>
      <Navbar.Segment align="start">
        <Navbar.Item as={NavLink} to="/" exact activeClassName="is-active">
          Home
        </Navbar.Item>
        <Navbar.Item as={NavLink} to="/search" exact activeClassName="is-active">
          Search
        </Navbar.Item>
      </Navbar.Segment>
    </Navbar.Menu>
  </Navbar>
)

```

**Comment by dfee** [comment]
Here is the [`NavLink` code](https://github.com/ReactTraining/react-router/blob/05a00851087d3f2ccc0fabb2145e85368683c07d/packages/react-router-dom/modules/NavLink.js).

It seems that `NavLink`, as a functional component, doesn't accept the `ref` attribute. That could either be solved by `NavLink` using `React.forwardRef` or moving back to a class component (the former is probably a better idea).

Anyway, [this answer](https://stackoverflow.com/a/46694860/465164) seems like the proper way to vet whether or not a component should receive a ref.

```ts
const canReceiveRef: (Component: uknonwn) => {
  return typeof Component !== 'string' && !Boolean(Component.prototype.render)
}
```

**Comment by dfee** [comment]
That should support `as='div'`, or `as={MyFunctionalComponent}` or `as={MyClassComponent}`.

**Comment by ReeganExE** [comment]
And the solution or work-around is?

**Comment by dfee** [comment]
Resolved in the `next` branch.

**Comment by HiFaraz** [comment]
Thanks for the fix @dfee , when is this being released?
