### ISSUE TITLE
Replace use of Partial types with optional properties

### ISSUE THREAD

**Issue by ntsim** [dfee/rbx#65]
When using a Jetbrains IDE like IntelliJ/WebStorm, imported components from rbx all seem to trigger warnings from the IDE inspection that checks for missing required attributes/props (on XML/HTML/JSX elements). Disabling this inspection is not desirable as it stops the IDE warning us in real situations where we are actually missing required attributes/props.

This seems to be due to the use of the `Partial` type in most component props and the IDE not being able to identify these props as optional. This also has an additional effect of causing imported components to autocomplete with all of these optional props pre-filled with placeholders (as if they were required).

Unfortunately, this is a bit of a blocker to using rbx as this makes it quite unfriendly to use in Jetbrains IDEs. Whilst this probably should be something that Jetbrains should improve, it is probably simpler for rbx to just replace its usages of `Partial` with optional properties. I would also personally say it's clearer than using `Partial` everywhere as well (although that's more of a taste thing).

**Comment by dfee** [comment]
Looking into this on Reactiflux's #typescript. Is this still an issues? I'm in-different to using `?` vs. `Partial` at this point, though it'd just require a bunch of updates in the code (noise).

**Comment by ntsim** [comment]
Yep this is still an issue with the latest version of IntelliJ/Jetbrains IDEs. See the following screenshots:

Inspection give false positives:
![image](https://user-images.githubusercontent.com/9917868/59350774-d857b600-8d14-11e9-9994-4c107ec71cc6.png)

Autocompleting on an rbx component pre-fills placeholders for every prop (even though they are all optional):
![image](https://user-images.githubusercontent.com/9917868/59350743-c8d86d00-8d14-11e9-9628-23184173378a.png)

**Comment by dfee** [comment]
Fixed in `next` branch. Will be available on `master` shortly.
