### ISSUE TITLE
Howto use responsive properties?

### ISSUE THREAD

**Issue by berrg** [dfee/rbx#68]
We have tried to use responsive properties to show and hide a container without success. Can you provide a working example?

This is our code which does not work:

`
<Container touch={{hide: {value: true}}} desktop={{hide: {value: false, only: true}}}>
  This text should be visible for devices above desktop breakpoint
</Container>
`

What is the correct syntax?

By the way, great work.

Best regards
Morten Berg

**Comment by dfee** [comment]
I ought to update the docs, but here is a code-sandbox reflecting how it works (the prop is `responsive`, not `touch` / `desktop`... those are keys within the responsive object.

https://codesandbox.io/s/rbx--tshtp
