### ISSUE TITLE
<Navbar/> typing in v2.2.0

### ISSUE THREAD

**Issue by jazzycamel** [dfee/rbx#88]
Upgraded from 2.1.0 to 2.2.0 and `<Navbar />` now throws the following typescript error irrespective of which properties are passed:

```
Type '{}' is missing the following properties from type 'Pick<any, "hidden" | "overlay" | "italic" | "relative" | "tooltip" | "className" | "badge" | "badgeColor" | "badgeOutlined" | "badgeRounded" | "badgeSize" | "clearfix" | "pull" | ... 25 more ... | "managed">
Failed to compile.
```

**Comment by dfee** [comment]
@jazzycamel I'm currently working on the `next` branch where I'm doing things like moving to hooks, and fixing a couple outstanding issues.

I'm not able to reproduce this issue, however. What is your setup? (including TypeScript version)
